Add probtest to CSCS-CI on Santis
https://gitlab.dkrz.de/icon/icon/-/merge_requests/557

This MR adds the probtest functionalities to CSCS-CI for Santis, as they are present in Buildbot. Therefore, probtest is being run in a container, which lives on docker.

Co-authored-by: Ralf Mueller <ralf.mueller@dkrz.de>
Approved-by: Daniel Hupp <daniel.hupp@meteoswiss.ch>
Approved-by: Sergey Kosukhin <sergey.kosukhin@mpimet.mpg.de>
Merged-by: Ralf Mueller <ralf.mueller@dkrz.de>

diff --git a/run/tolerance/check_tolerance b/run/tolerance/check_tolerance
--- a/run/tolerance/check_tolerance
+++ b/run/tolerance/check_tolerance
@@ -97,51 +97,65 @@ probtest_file_id=($(${SCRIPT_DIR}/../../scripts/experiments/get_probtest_file_id
 
 echo "Running tolerance check with compiler-specific reference at ${CPU_REFERENCE}"
 
-LOG=probtest_${EXPERIMENT}.log
+if [[ "${builder}" == santis* ]]; then
+    # Generate stats file from base directory
+    python3 scripts/cscs_ci/probtest_container_wrapper.py stats "$EXPERIMENT" \
+      --build-dir "${MODEL_DIR1}" \
+      --member-name "${EXP_BASE}" \
+      --stats-file-path "${EXPERIMENT}.csv"
 
-export PROBTEST_CONFIG=${EXP_BASE}.json
-# initialize configuration file
-if ! "${PROBTEST}" --log-file "${LOG}.init" init \
-    --codebase-install "${MODEL_DIR1}" \
-    --reference "not-used" \
-    --experiment-name "${EXP_BASE}" \
-    "${probtest_file_id[@]}"  \
-    --config "${PROBTEST_CONFIG}"
-then
-    echo "probtest did not initialized successfully"
-    exit 1
+    # Run tolerance check
+    python3 scripts/cscs_ci/probtest_container_wrapper.py check "$EXPERIMENT" \
+      --input-file-cur "${EXPERIMENT}.csv" \
+      --input-file-ref "${CPU_REFERENCE}/${EXPERIMENT}_reference.csv" \
+      --tolerance-file-name "${CPU_REFERENCE}/${EXPERIMENT}_tolerance.csv"
+else
+    LOG=probtest_${EXPERIMENT}.log
+
+    export PROBTEST_CONFIG=${EXP_BASE}.json
+    # initialize configuration file
+    if ! "${PROBTEST}" --log-file "${LOG}.init" init \
+        --codebase-install "${MODEL_DIR1}" \
+        --reference "not-used" \
+        --experiment-name "${EXP_BASE}" \
+        "${probtest_file_id[@]}"  \
+        --config "${PROBTEST_CONFIG}"
+    then
+        echo "probtest did not initialized successfully"
+        exit 1
+    fi
+
+    # generate the aggregated "single-column" stats file
+    if ! "${PROBTEST}" --log-file "${LOG}.stats" stats \
+        --stats-file-name "${EXPERIMENT}.csv" \
+        --no-ensemble
+    then
+        echo "probtest did not generate stats successfully"
+        exit 1
+    fi
+
+    # validate the generated stats against the reference
+    if ! "${PROBTEST}" --log-file "${LOG}.check" check \
+        --input-file-cur "${EXPERIMENT}.csv" \
+        --input-file-ref "${CPU_REFERENCE}/${EXPERIMENT}_reference.csv" \
+        --tolerance-file-name "${CPU_REFERENCE}/${EXPERIMENT}_tolerance.csv" \
+        --factor $FACTOR
+    then
+        echo "probtest tolerance test did not complete successfully"
+        exit 1
+    fi
+
+    # get the relevant success check
+    fail=$(grep -c "RESULT.*FAIL" "${LOG}.check" || true)
+    crash=$(grep -c "RESULT.*CRASH" "${LOG}.check" || true)
+    finished=$(grep -c RESULT "${LOG}.check" || true)
+    if [[ $(($fail+$crash)) -gt 0 || $((finished)) -lt 1 ]] ; then
+        cat "${LOG}.check"
+        echo "probtest did not complete successfully"
+        exit 1
+    fi
+
+    echo "probtest complete successfully"
+
+    exit 0
 fi
-
-# generate the aggregated "single-column" stats file
-if ! "${PROBTEST}" --log-file "${LOG}.stats" stats \
-    --stats-file-name "${EXPERIMENT}.csv" \
-    --no-ensemble
-then
-    echo "probtest did not generate stats successfully"
-    exit 1
-fi
-
-# validate the generated stats against the reference
-if ! "${PROBTEST}" --log-file "${LOG}.check" check \
-    --input-file-cur "${EXPERIMENT}.csv" \
-    --input-file-ref "${CPU_REFERENCE}/${EXPERIMENT}_reference.csv" \
-    --tolerance-file-name "${CPU_REFERENCE}/${EXPERIMENT}_tolerance.csv" \
-    --factor $FACTOR
-then
-    echo "probtest tolerance test did not complete successfully"
-    exit 1
-fi
-
-# get the relevant success check
-fail=$(grep -c "RESULT.*FAIL" "${LOG}.check" || true)
-crash=$(grep -c "RESULT.*CRASH" "${LOG}.check" || true)
-finished=$(grep -c RESULT "${LOG}.check" || true)
-if [[ $(($fail+$crash)) -gt 0 || $((finished)) -lt 1 ]] ; then
-    cat "${LOG}.check"
-    echo "probtest did not complete successfully"
-    exit 1
-fi
-
-echo "probtest complete successfully"
-
-exit 0
